services:
  - type: web
    name: ekommerce-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: PRODUCTION
      - key: PORT
        value: 10000
    autoDeploy: false
