services:
  - type: web
    name: ekommerce-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: ./backend
    buildCommand: npm install --production=false
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: PRODUCTION
      - key: PORT
        value: 10000
    autoDeploy: false
